export const endpoints = {
  overview: '/admin/overview',
  listings: '/admin/listings',
  orders: '/admin/orders',
  inspections: '/admin/inspections',
  disputes: '/admin/disputes',
  withdrawals: '/admin/withdrawals',
  transfers: '/admin/transfers',
  statement: '/admin/wallet-statement',
  compensation: '/admin/compensation',
  bankbook: '/admin/bank-movements',
  closing: '/admin/daily-closing',
  invoices: '/admin/invoices',
  pricing: '/admin/gold-pricing',
  rates: '/admin/commission-rates',
  promos: '/admin/promo-codes',
  marketMaker: '/admin/market-maker',
  karats: '/admin/karats',
  switches: '/admin/switches',
  branches: '/admin/branches',
  content: '/admin/app-text',
  docs: '/admin/documents',
  customer: '/admin/customer',
  users: '/admin/users',
  staff: '/admin/staff',
  audit: '/admin/audit',
} as const

export type EndpointKey = keyof typeof endpoints
